### ISSUE TITLE
TypeError: Cannot read property '_domId' of null

### ISSUE THREAD

**Issue by webleaf** [NativeScript/template-blank-ts#49]
`$ tns create my-blank-ts --template https://github.com/NativeScript/template-blank-ts`
`$ tns run android --bundle`
```
ActivityManager: Start proc 31358:org.nativescript.myblankts/u0a471 for activity org.nativescript.myblankts/com.tns.NativeScriptActivity
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.myblankts/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: 
System.err: TypeError: Cannot read property '_domId' of null
System.err: File: "file:///data/data/org.nativescript.myblankts/files/app/vendor.js, line: 20910, column: 45
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'__dirname.push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.myblankts/files/app/vendor.js', line: 20910, column: 46
System.err: 	Frame: function:'__dirname.push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.myblankts/files/app/vendor.js', line: 20759, column: 14
System.err: 	Frame: function:'__dirname.push.../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.myblankts/files/app/vendor.js', line: 18788, column: 25
System.err: 
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
System.err: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: 
System.err: TypeError: Cannot read property '_domId' of null
System.err: File: "file:///data/data/org.nativescript.myblankts/files/app/vendor.js, line: 20910, column: 45
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'__dirname.push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.myblankts/files/app/vendor.js', line: 20910, column: 46
System.err: 	Frame: function:'__dirname.push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.myblankts/files/app/vendor.js', line: 20759, column: 14
System.err: 	Frame: function:'__dirname.push.../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.myblankts/files/app/vendor.js', line: 18788, column: 25
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err: 	at android.app.Activity.performCreate(Activity.java:6956)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
System.err: 	... 9 more
ActivityManager: Process org.nativescript.myblankts (pid 31358) has died(63,640)
ActivityManager: cleanUpApplicationRecord -- 31358
```

**Comment by webleaf** [comment]
works after `tns update next`
